@startuml
start

while (stop condition not met?) is (No)

  :select genomes to test;

  fork 
  :run in parallel;
  while (execution period is up?) is (No)
    :mutate genome;
    :insert into array if better;

  endwhile (Yes)
  end merge
  :save the best genomes, also save if the branch of genomes \n have been run previosly and if there is an improvement;

endwhile (Yes)

:return the best genome to the caller;

stop
@enduml
