@startuml
start

:measure for determinism; 

while (stop condition not met?)

  :select genomes to test;

  fork 
  :run in parallel;
  while (time interval specified not met?)

  if (deteministic scores) then (Yes)
    :insert into array if better;
  else (No)
    :use statistical method t-test to determine if it is an improvement;
  endif

  endwhile
  end merge
  :save the best genomes, also save if the branch of genomes \n have been run previosly and if there is an improvement;

endwhile

stop
@enduml
